"use client";

import React, { useState, useEffect, useMemo } from "react";
import { motion, AnimatePresence, useReducedMotion } from "framer-motion";
import { createPortal } from "react-dom";
import type { ChatMessage } from "@/types/chat";
import { useNexusStore } from "@/state/nexusStore";
import jsPDF from "jspdf";

interface ChatSummaryProps {
  messages: ChatMessage[];
  sessionId: string;
  onSummaryGenerated?: (summary: string) => void;
  onAddToChat?: (content: string) => void;
}

interface SummaryData {
  quickLook: string;
  keyTopics: string[];
  actionItems: string[];
  userPreferences: string[];
  fullSummary: string;
}

// Helper function to detect if content is Arabic
function isArabic(text: string): boolean {
  const arabicRegex = /[\u0600-\u06FF]/;
  return arabicRegex.test(text);
}

// Detect primary language of conversation
function detectLanguage(messages: ChatMessage[]): "ar" | "en" {
  const allText = messages.map(m => m.content).join(" ");
  return isArabic(allText) ? "ar" : "en";
}

// Arabic translations
const translations = {
  ar: {
    title: "ملخص المحادثة",
    quickLook: "نظرة سريعة",
    keyTopics: "المواضيع الرئيسية",
    actionItems: "بنود العمل",
    userPreferences: "تفضيلات المستخدم",
    fullSummary: "الملخص الكامل",
    generate: "توليد الملخص",
    generating: "جاري التوليد...",
    copy: "نسخ",
    copied: "تم النسخ!",
    exportPDF: "تصدير PDF",
    exportMD: "تصدير Markdown",
    close: "إغلاق",
    expand: "توسيع",
    collapse: "طي",
    noMessages: "تحتاج إلى رسالتين على الأقل لتوليد الملخص",
    error: "فشل في توليد الملخص. يرجى المحاولة مرة أخرى.",
    generatedBy: "تم التوليد بواسطة NEXUS",
    autoUpdate: "تحديث تلقائي",
    manualUpdate: "تحديث يدوي",
    lastUpdated: "آخر تحديث",
    showInChat: "عرض في الشات",
    hideFromChat: "إخفاء من الشات",
  },
  en: {
    title: "Conversation Summary",
    quickLook: "Quick Look",
    keyTopics: "Key Topics",
    actionItems: "Action Items",
    userPreferences: "User Preferences",
    fullSummary: "Full Summary",
    generate: "Generate Summary",
    generating: "Generating...",
    copy: "Copy",
    copied: "Copied!",
    exportPDF: "Export PDF",
    exportMD: "Export Markdown",
    close: "Close",
    expand: "Expand",
    collapse: "Collapse",
    noMessages: "Need at least 2 messages to generate a summary",
    error: "Failed to generate summary. Please try again.",
    generatedBy: "Generated by NEXUS",
    autoUpdate: "Auto Update",
    manualUpdate: "Manual Update",
    lastUpdated: "Last Updated",
    showInChat: "Show in Chat",
    hideFromChat: "Hide from Chat",
  },
};

export const ChatSummary = React.memo(function ChatSummary({ messages, sessionId, onSummaryGenerated, onAddToChat }: ChatSummaryProps) {
  // sessionId is kept for future use but currently not used
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const _sessionId = sessionId;
  const { getActiveSession, updateSessionSummary } = useNexusStore();
  const activeSession = getActiveSession();
  
  // Detect language
  const lang = useMemo(() => detectLanguage(messages), [messages]);
  const t = translations[lang];
  
  const shouldReduceMotion = useReducedMotion();
  
  // Load saved summary from session
  const savedSummary = activeSession?.summary;
  const [summaryData, setSummaryData] = useState<SummaryData | null>(() => {
    if (savedSummary) {
      try {
        const parsed = JSON.parse(savedSummary) as SummaryData;
        parsed.keyTopics = parsed.keyTopics || [];
        parsed.actionItems = parsed.actionItems || [];
        parsed.userPreferences = parsed.userPreferences || [];
        parsed.quickLook = parsed.quickLook || "";
        parsed.fullSummary = parsed.fullSummary || "";
        return parsed;
      } catch {
        return null;
      }
    }
    return null;
  });
  
  const [isLoading, setIsLoading] = useState(false);
  const [isPopupOpen, setIsPopupOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const [showInChat, setShowInChat] = useState(!!savedSummary);
  const [expandedSections, setExpandedSections] = useState({
    quickLook: true,
    keyTopics: true,
    actionItems: true,
    userPreferences: true,
    fullSummary: true
  });
  const [lastUpdated, setLastUpdated] = useState<number | null>(null);

  // Note: Auto-update removed - users can manually update when needed

  // Load summary from session on mount
  useEffect(() => {
    if (activeSession?.summary && !summaryData) {
      try {
        const parsed = JSON.parse(activeSession.summary) as SummaryData;
        parsed.keyTopics = parsed.keyTopics || [];
        parsed.actionItems = parsed.actionItems || [];
        parsed.userPreferences = parsed.userPreferences || [];
        parsed.quickLook = parsed.quickLook || "";
        parsed.fullSummary = parsed.fullSummary || "";
        setSummaryData(parsed);
        setShowInChat(true);
      } catch {
        // Invalid summary, ignore
      }
    }
  }, [activeSession?.summary, summaryData]);

  const [retryCount, setRetryCount] = useState(0);

  const generateSummary = React.useCallback(async (silent = false) => {
    if (messages.length < 2) {
      if (!silent) {
        alert(t.noMessages);
      }
      return;
    }

    setIsLoading(true);
    try {
      const response = await fetch("/api/nexus/summarize", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          messages: messages.map((m) => ({ role: m.role, content: m.content })),
        }),
      });

      if (!response.ok) throw new Error("Failed to generate summary");

      const data = await response.json() as SummaryData;
      // Ensure arrays exist
      data.keyTopics = Array.isArray(data.keyTopics) ? data.keyTopics : [];
      data.actionItems = Array.isArray(data.actionItems) ? data.actionItems : [];
      data.userPreferences = Array.isArray(data.userPreferences) ? data.userPreferences : [];
      // Ensure strings exist
      data.quickLook = data.quickLook || "";
      data.fullSummary = data.fullSummary || "";
      
      setSummaryData(data);
      setLastUpdated(Date.now());
      setRetryCount(0); // Reset retry count on success
      
      // Save to session
      updateSessionSummary(JSON.stringify(data));
      
      // Format summary as a message
      const summaryText = lang === "ar" 
        ? `## 📋 ملخص المحادثة\n\n**${t.quickLook}:**\n${data.quickLook}\n\n**${t.keyTopics}:**\n${(data.keyTopics || []).map(t => `• ${t}`).join("\n")}\n\n**${t.actionItems}:**\n${(data.actionItems || []).map(a => `✓ ${a}`).join("\n")}\n\n**${t.userPreferences}:**\n${(data.userPreferences || []).map(p => `⭐ ${p}`).join("\n")}\n\n**${t.fullSummary}:**\n${data.fullSummary}`
        : `## 📋 Conversation Summary\n\n**${t.quickLook}:**\n${data.quickLook}\n\n**${t.keyTopics}:**\n${(data.keyTopics || []).map(t => `• ${t}`).join("\n")}\n\n**${t.actionItems}:**\n${(data.actionItems || []).map(a => `✓ ${a}`).join("\n")}\n\n**${t.userPreferences}:**\n${(data.userPreferences || []).map(p => `⭐ ${p}`).join("\n")}\n\n**${t.fullSummary}:**\n${data.fullSummary}`;
      
      // Add to chat if enabled
      if (showInChat && onAddToChat) {
        onAddToChat(summaryText);
      } else if (!silent && !showInChat) {
        // Show popup if not showing in chat
        setIsPopupOpen(true);
      }
      
      onSummaryGenerated?.(data.fullSummary);
    } catch (error) {
      console.error("Failed to generate summary:", error);
      if (!silent) {
        // Only show alert if we've retried a few times or it's a manual trigger
        if (retryCount >= 2) {
          alert(t.error);
        } else {
          // Auto-retry maybe? Or just show error state in UI
        }
      }
    } finally {
      setIsLoading(false);
    }
  }, [messages, t, lang, showInChat, onAddToChat, onSummaryGenerated, retryCount, updateSessionSummary]);

  // Auto-generate summary if enough messages and no summary exists
  useEffect(() => {
    if (messages.length >= 10 && !summaryData && !activeSession?.summary && !isLoading && sessionId) {
      const timer = setTimeout(() => {
        generateSummary(true);
      }, 3000);
      return () => clearTimeout(timer);
    }
  }, [messages.length, summaryData, activeSession?.summary, isLoading, sessionId, generateSummary]);

  const copySummary = async () => {
    if (!summaryData) return;
    
    const textToCopy = lang === "ar"
      ? `${t.quickLook}\n${summaryData.quickLook}\n\n${t.keyTopics}\n${(summaryData.keyTopics || []).join("\n")}\n\n${t.actionItems}\n${(summaryData.actionItems || []).join("\n")}\n\n${t.userPreferences}\n${(summaryData.userPreferences || []).join("\n")}\n\n${t.fullSummary}\n${summaryData.fullSummary}`
      : `QUICK LOOK\n${summaryData.quickLook}\n\nKEY TOPICS\n${(summaryData.keyTopics || []).join("\n")}\n\nACTION ITEMS\n${(summaryData.actionItems || []).join("\n")}\n\nUSER PREFERENCES\n${(summaryData.userPreferences || []).join("\n")}\n\nFULL SUMMARY\n${summaryData.fullSummary}`;
    
    try {
      await navigator.clipboard.writeText(textToCopy);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const toggleSection = (section: keyof typeof expandedSections) => {
    setExpandedSections(prev => ({
      ...prev,
      [section]: !prev[section]
    }));
  };

  const exportToPDF = () => {
    if (!summaryData) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let yPos = margin;

    // Title
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(t.title, pageWidth / 2, yPos, { align: "center" });
    yPos += 15;

    // Quick Look
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(t.quickLook, margin, yPos);
    yPos += 8;
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    const quickLookLines = doc.splitTextToSize(summaryData.quickLook, pageWidth - 2 * margin);
    doc.text(quickLookLines, margin, yPos);
    yPos += quickLookLines.length * 6 + 10;

    // Key Topics
    if ((summaryData.keyTopics || []).length > 0) {
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text(t.keyTopics, margin, yPos);
      yPos += 8;
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      (summaryData.keyTopics || []).forEach((topic) => {
        doc.text(`• ${topic}`, margin + 5, yPos);
        yPos += 6;
      });
      yPos += 5;
    }

    // Action Items
    if ((summaryData.actionItems || []).length > 0) {
      if (yPos > 250) {
        doc.addPage();
        yPos = margin;
      }
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text(t.actionItems, margin, yPos);
      yPos += 8;
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      (summaryData.actionItems || []).forEach((item) => {
        doc.text(`• ${item}`, margin + 5, yPos);
        yPos += 6;
      });
      yPos += 5;
    }

    // User Preferences
    if ((summaryData.userPreferences || []).length > 0) {
      if (yPos > 250) {
        doc.addPage();
        yPos = margin;
      }
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text(t.userPreferences, margin, yPos);
      yPos += 8;
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      (summaryData.userPreferences || []).forEach((pref) => {
        doc.text(`• ${pref}`, margin + 5, yPos);
        yPos += 6;
      });
      yPos += 5;
    }

    // Full Summary
    if (yPos > 250) {
      doc.addPage();
      yPos = margin;
    }
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(t.fullSummary, margin, yPos);
    yPos += 8;
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    const summaryLines = doc.splitTextToSize(summaryData.fullSummary, pageWidth - 2 * margin);
    doc.text(summaryLines, margin, yPos);

    doc.save(`conversation-summary-${Date.now()}.pdf`);
  };

  const exportToMarkdown = () => {
    if (!summaryData) return;
    
    const text = lang === "ar"
      ? `# ${t.title}\n\n**${t.quickLook}**\n${summaryData.quickLook}\n\n**${t.keyTopics}**\n${(summaryData.keyTopics || []).map(t => `- ${t}`).join("\n")}\n\n**${t.actionItems}**\n${(summaryData.actionItems || []).map(i => `- [ ] ${i}`).join("\n")}\n\n**${t.userPreferences}**\n${(summaryData.userPreferences || []).map(p => `- ${p}`).join("\n")}\n\n**${t.fullSummary}**\n${summaryData.fullSummary}`
      : `# ${t.title}\n\n**${t.quickLook}**\n${summaryData.quickLook}\n\n**${t.keyTopics}**\n${(summaryData.keyTopics || []).map(t => `- ${t}`).join("\n")}\n\n**${t.actionItems}**\n${(summaryData.actionItems || []).map(i => `- [ ] ${i}`).join("\n")}\n\n**${t.userPreferences}**\n${(summaryData.userPreferences || []).map(p => `- ${p}`).join("\n")}\n\n**${t.fullSummary}**\n${summaryData.fullSummary}`;

    const blob = new Blob([text], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `conversation-summary-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const formatTime = (timestamp: number) => {
    const date = new Date(timestamp);
    return lang === "ar"
      ? date.toLocaleString("ar-SA", { 
          year: "numeric", 
          month: "short", 
          day: "numeric", 
          hour: "2-digit", 
          minute: "2-digit" 
        })
      : date.toLocaleString("en-US", { 
          year: "numeric", 
          month: "short", 
          day: "numeric", 
          hour: "2-digit", 
          minute: "2-digit" 
        });
  };

  // Show skeleton if loading and no data yet
  if (isLoading && !summaryData && showInChat) {
    return <ChatSummarySkeleton />;
  }

  // Show summary in chat if enabled
  if (showInChat && summaryData) {
    return (
      <div className="mb-4 rounded-xl border border-purple-500/20 bg-gradient-to-r from-purple-500/5 to-fuchsia-500/5 p-4 backdrop-blur-xl">
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <svg className="w-5 h-5 text-purple-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            <span className="text-sm font-semibold text-purple-300">{t.title}</span>
            {lastUpdated && (
              <span className="text-xs text-purple-400/60">
                {t.lastUpdated}: {formatTime(lastUpdated)}
              </span>
            )}
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => generateSummary(false)}
              disabled={isLoading}
              className="px-3 py-1.5 text-xs bg-gradient-to-r from-purple-600/20 to-fuchsia-600/20 hover:from-purple-600/30 hover:to-fuchsia-600/30 text-purple-200 rounded-lg transition-all duration-300 disabled:opacity-50 hover:scale-105 active:scale-95 border border-purple-500/30 hover:border-purple-400/50"
              title={t.generate}
            >
              {isLoading ? (
                <div className="flex items-center gap-1.5">
                  <svg className="animate-spin h-3 w-3 text-purple-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  <span className="text-[10px] font-medium">{t.generating}</span>
                </div>
              ) : (
                <div className="flex items-center gap-1.5">
                  <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                  </svg>
                  <span className="text-[10px] font-medium">{t.generate}</span>
                </div>
              )}
            </button>
            <button
              onClick={() => setShowInChat(false)}
              className="px-3 py-1.5 text-xs bg-white/5 hover:bg-white/10 text-white/60 rounded-lg transition-all duration-300 hover:scale-105 active:scale-95 border border-white/10 hover:border-white/20"
              title={t.hideFromChat}
            >
              <div className="flex items-center gap-1.5">
                <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
                <span className="text-[10px] font-medium">{t.hideFromChat}</span>
              </div>
            </button>
            <button
              onClick={() => setIsPopupOpen(true)}
              className="px-3 py-1.5 text-xs bg-gradient-to-r from-purple-600/30 via-fuchsia-600/25 to-purple-600/30 hover:from-purple-600/40 hover:via-fuchsia-600/35 hover:to-purple-600/40 text-purple-100 rounded-lg transition-all duration-300 hover:scale-105 active:scale-95 border border-purple-500/40 hover:border-purple-400/60 hover:shadow-[0_0_15px_rgba(168,85,247,0.2)]"
            >
              <div className="flex items-center gap-1.5">
                <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5v-4m0 4h-4m4 0l-5-5" />
                </svg>
                <span className="text-[10px] font-medium">{t.expand}</span>
              </div>
            </button>
          </div>
        </div>

        {/* Quick Look */}
        <div className="mb-4 rounded-xl border border-cyan-500/30 bg-gradient-to-br from-cyan-500/10 to-cyan-900/5 p-4 backdrop-blur-sm">
          <div className="flex items-center gap-2 mb-3">
            <div className="p-1.5 rounded-lg bg-cyan-500/20 border border-cyan-400/30">
              <svg className="h-4 w-4 text-cyan-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
              </svg>
            </div>
            <h3 className="text-xs font-bold uppercase tracking-wider text-cyan-300 bg-gradient-to-r from-cyan-300 to-cyan-200 bg-clip-text text-transparent">{t.quickLook}</h3>
          </div>
          <p className="text-sm leading-relaxed text-white/90 pl-2 border-l-2 border-cyan-500/30">{summaryData.quickLook}</p>
        </div>

        {/* Key Topics */}
        {(summaryData.keyTopics || []).length > 0 && (
          <div className="mb-4">
            <div className="flex items-center gap-2 mb-3">
              <div className="p-1.5 rounded-lg bg-purple-500/20 border border-purple-400/30">
                <svg className="h-4 w-4 text-purple-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 20l4-16m2 16l4-16M6 9h14M4 15h14" />
                </svg>
              </div>
              <h3 className="text-xs font-bold uppercase tracking-wider text-purple-300 bg-gradient-to-r from-purple-300 to-fuchsia-200 bg-clip-text text-transparent">{t.keyTopics}</h3>
            </div>
            <div className="flex flex-wrap gap-2">
              {(summaryData.keyTopics || []).slice(0, 4).map((topic, idx) => (
                <span key={idx} className="px-3 py-1.5 rounded-xl border border-purple-500/30 bg-gradient-to-r from-purple-500/10 to-fuchsia-500/5 text-xs font-medium text-purple-200 hover:from-purple-500/20 hover:to-fuchsia-500/10 transition-all duration-300 hover:scale-105 hover:shadow-[0_0_15px_rgba(168,85,247,0.15)]">
                  • {topic}
                </span>
              ))}
              {(summaryData.keyTopics || []).length > 4 && (
                <span className="px-3 py-1.5 rounded-xl border border-purple-500/40 bg-gradient-to-r from-purple-600/20 to-fuchsia-600/15 text-xs font-medium text-purple-300 hover:shadow-[0_0_15px_rgba(168,85,247,0.2)] transition-all">
                  +{(summaryData.keyTopics || []).length - 4} {lang === "ar" ? "أخرى" : "more"}
                </span>
              )}
            </div>
          </div>
        )}

        {/* Action Items */}
        {(summaryData.actionItems || []).length > 0 && (
          <div className="mb-4">
            <div className="flex items-center gap-2 mb-3">
              <div className="p-1.5 rounded-lg bg-emerald-500/20 border border-emerald-400/30">
                <svg className="h-4 w-4 text-emerald-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
              <h3 className="text-xs font-bold uppercase tracking-wider text-emerald-300 bg-gradient-to-r from-emerald-300 to-cyan-200 bg-clip-text text-transparent">{t.actionItems}</h3>
            </div>
            <div className="space-y-2">
              {(summaryData.actionItems || []).slice(0, 3).map((item, idx) => (
                <div key={idx} className="flex items-start gap-3 p-2 rounded-lg border border-emerald-500/20 bg-gradient-to-r from-emerald-500/5 to-emerald-900/5 hover:from-emerald-500/10 hover:to-emerald-900/10 transition-all duration-300 group">
                  <div className="p-1 rounded-md bg-emerald-500/20 border border-emerald-400/30 group-hover:bg-emerald-500/30 group-hover:border-emerald-400/50 transition-colors">
                    <svg className="h-3 w-3 text-emerald-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                  </div>
                  <span className="text-xs font-medium text-white/90 flex-1">{item}</span>
                </div>
              ))}
              {(summaryData.actionItems || []).length > 3 && (
                <div className="text-xs font-medium text-emerald-300/70 text-center pt-1">
                  +{(summaryData.actionItems || []).length - 3} {lang === "ar" ? "بنود عمل أخرى" : "more action items"}
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    );
  }

  // Summary generation button (when no summary exists or hidden)
  return (
    <>
      <div className="mb-4 rounded-xl border border-purple-500/20 bg-gradient-to-r from-purple-500/5 to-fuchsia-500/5 p-3 backdrop-blur-xl">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <svg className="w-4 h-4 text-purple-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            <span className="text-xs font-semibold text-purple-300">{t.title}</span>
          </div>
          <button
            onClick={() => generateSummary(false)}
            disabled={isLoading}
            className="px-4 py-2 text-xs font-medium bg-gradient-to-r from-purple-600/40 via-fuchsia-600/30 to-purple-600/40 hover:from-purple-600/50 hover:via-fuchsia-600/40 hover:to-purple-600/50 text-purple-100 rounded-xl transition-all duration-300 disabled:opacity-50 transform-gpu will-change-transform border border-purple-500/40 hover:border-purple-400/60 hover:shadow-[0_0_20px_rgba(168,85,247,0.3)] hover:scale-105 active:scale-95 group relative overflow-hidden"
          >
            {/* Shine effect */}
            <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/20 to-transparent translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-1000" />
            
            {isLoading ? (
              <div className="flex items-center gap-2 relative z-10">
                <svg className="animate-spin h-3.5 w-3.5 text-purple-200" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                <span className="font-semibold">{t.generating}</span>
              </div>
            ) : (
              <div className="flex items-center gap-2 relative z-10">
                <svg className="w-3.5 h-3.5 text-purple-200" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                <span className="font-semibold">{t.generate}</span>
              </div>
            )}
          </button>
        </div>
      </div>

      {/* Glassmorphism Popup */}
      {typeof window !== "undefined" && createPortal(
        <AnimatePresence>
          {isPopupOpen && summaryData && (
            <>
              {/* Backdrop */}
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: shouldReduceMotion ? 0 : 0.2 }}
                className="fixed inset-0 z-[99998] bg-black/60 backdrop-blur-sm"
                onClick={() => setIsPopupOpen(false)}
                aria-hidden="true"
              />

              {/* Popup */}
              <motion.div
                initial={{ opacity: 0, scale: shouldReduceMotion ? 1 : 0.95, y: shouldReduceMotion ? 0 : 20 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                exit={{ opacity: 0, scale: shouldReduceMotion ? 1 : 0.95, y: shouldReduceMotion ? 0 : 20 }}
                transition={shouldReduceMotion ? { duration: 0 } : { type: "spring", damping: 25, stiffness: 300 }}
                className="fixed left-1/2 top-1/2 z-[99999] w-[90vw] max-w-2xl -translate-x-1/2 -translate-y-1/2 rounded-3xl border border-white/20 bg-black/80 backdrop-blur-2xl shadow-2xl shadow-black/50 transform-gpu will-change-transform"
                role="dialog"
                aria-modal="true"
                aria-label={t.title}
                dir={lang === "ar" ? "rtl" : "ltr"}
              >
                {/* Header */}
                <div className="flex items-center justify-between border-b border-white/10 bg-black/40 p-5">
                  <h2 className="text-lg font-bold tracking-wide text-white/90">{t.title}</h2>
                  <div className="flex items-center gap-2">
                    {lastUpdated && (
                      <span className="text-xs text-white/40">
                        {t.lastUpdated}: {formatTime(lastUpdated)}
                      </span>
                    )}
                    <button
                      onClick={() => setIsPopupOpen(false)}
                      className="rounded-lg p-1.5 text-white/50 transition-colors hover:bg-white/10 hover:text-white"
                      aria-label={t.close}
                    >
                      <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                      </svg>
                    </button>
                  </div>
                </div>

                {/* Content */}
                <div className="max-h-[70vh] overflow-y-auto p-5 [scrollbar-width:none] [-ms-overflow-style:none] [&::-webkit-scrollbar]:hidden">
                  {/* Quick Look Card */}
                  <div className="mb-6 rounded-2xl border border-cyan-500/30 bg-gradient-to-br from-cyan-500/10 to-purple-500/10 p-4 backdrop-blur-xl">
                    <div className="mb-2 flex items-center justify-between gap-2">
                      <div className="flex items-center gap-2">
                        <svg className="h-5 w-5 text-cyan-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                        </svg>
                        <h3 className="text-sm font-bold uppercase tracking-wider text-cyan-300">{t.quickLook}</h3>
                      </div>
                      <button 
                        onClick={() => toggleSection('quickLook')}
                        className="text-white/50 hover:text-white transition-colors"
                      >
                        {expandedSections.quickLook ? (
                          <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" />
                          </svg>
                        ) : (
                          <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                          </svg>
                        )}
                      </button>
                    </div>
                    {expandedSections.quickLook && (
                      <p className="text-sm leading-relaxed text-white/90">{summaryData.quickLook}</p>
                    )}
                  </div>

                  {/* Key Topics */}
                  {(summaryData.keyTopics || []).length > 0 && (
                    <div className="mb-6">
                      <div className="flex items-center justify-between mb-3">
                        <h3 className="text-sm font-bold uppercase tracking-wider text-purple-300">{t.keyTopics}</h3>
                        <button 
                          onClick={() => toggleSection('keyTopics')}
                          className="text-white/50 hover:text-white transition-colors"
                        >
                          {expandedSections.keyTopics ? (
                            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" />
                            </svg>
                          ) : (
                            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                            </svg>
                          )}
                        </button>
                      </div>
                      {expandedSections.keyTopics && (
                        <div className="space-y-2">
                          {(summaryData.keyTopics || []).map((topic, idx) => (
                            <div key={idx} className="rounded-lg border border-white/10 bg-white/5 px-4 py-2 text-sm text-white/80">
                              • {topic}
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  )}

                  {/* Action Items */}
                  {(summaryData.actionItems || []).length > 0 && (
                    <div className="mb-6">
                      <div className="flex items-center justify-between mb-3">
                        <h3 className="text-sm font-bold uppercase tracking-wider text-emerald-300">{t.actionItems}</h3>
                        <button 
                          onClick={() => toggleSection('actionItems')}
                          className="text-white/50 hover:text-white transition-colors"
                        >
                          {expandedSections.actionItems ? (
                            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" />
                            </svg>
                          ) : (
                            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                            </svg>
                          )}
                        </button>
                      </div>
                      {expandedSections.actionItems && (
                        <div className="space-y-2">
                          {(summaryData.actionItems || []).map((item, idx) => (
                            <div key={idx} className="rounded-lg border border-emerald-500/20 bg-emerald-500/5 px-4 py-2 text-sm text-white/80">
                              ✓ {item}
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  )}

                  {/* User Preferences */}
                  {(summaryData.userPreferences || []).length > 0 && (
                    <div className="mb-6">
                      <div className="flex items-center justify-between mb-3">
                        <h3 className="text-sm font-bold uppercase tracking-wider text-fuchsia-300">{t.userPreferences}</h3>
                        <button 
                          onClick={() => toggleSection('userPreferences')}
                          className="text-white/50 hover:text-white transition-colors"
                        >
                          {expandedSections.userPreferences ? (
                            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" />
                            </svg>
                          ) : (
                            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                            </svg>
                          )}
                        </button>
                      </div>
                      {expandedSections.userPreferences && (
                        <div className="space-y-2">
                          {(summaryData.userPreferences || []).map((pref, idx) => (
                            <div key={idx} className="rounded-lg border border-fuchsia-500/20 bg-fuchsia-500/5 px-4 py-2 text-sm text-white/80">
                              ⭐ {pref}
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  )}

                  {/* Full Summary */}
                  <div>
                    <div className="flex items-center justify-between mb-3">
                      <h3 className="text-sm font-bold uppercase tracking-wider text-white/70">{t.fullSummary}</h3>
                      <button 
                        onClick={() => toggleSection('fullSummary')}
                        className="text-white/50 hover:text-white transition-colors"
                      >
                        {expandedSections.fullSummary ? (
                          <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" />
                          </svg>
                        ) : (
                          <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                          </svg>
                        )}
                      </button>
                    </div>
                    {expandedSections.fullSummary && (
                      <p className="text-sm leading-relaxed text-white/80 whitespace-pre-wrap">{summaryData.fullSummary}</p>
                    )}
                  </div>
                </div>

                {/* Footer Actions */}
                <div className="flex items-center justify-between border-t border-white/10 bg-black/40 p-5">
                  <div className="text-xs text-white/40">
                    {t.generatedBy}
                  </div>
                  <div className="flex items-center gap-3">
                    <button
                      onClick={() => {
                        setShowInChat(true);
                        setIsPopupOpen(false);
                      }}
                      className="flex items-center gap-2 rounded-lg border border-purple-500/30 bg-purple-500/10 px-4 py-2 text-sm font-medium text-purple-300 transition-all hover:bg-purple-500/20"
                    >
                      <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
                      </svg>
                      {t.showInChat}
                    </button>
                    <button
                      onClick={copySummary}
                      className="flex items-center gap-2 rounded-lg border border-cyan-500/30 bg-cyan-500/10 px-4 py-2 text-sm font-medium text-cyan-300 transition-all hover:bg-cyan-500/20"
                    >
                      <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                      </svg>
                      {copied ? t.copied : t.copy}
                    </button>
                    <button
                      onClick={exportToPDF}
                      className="flex items-center gap-2 rounded-lg border border-purple-500/30 bg-purple-500/10 px-4 py-2 text-sm font-medium text-purple-300 transition-all hover:bg-purple-500/20"
                    >
                      <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                      </svg>
                      {t.exportPDF}
                    </button>
                    <button
                      onClick={exportToMarkdown}
                      className="flex items-center gap-2 rounded-lg border border-fuchsia-500/30 bg-fuchsia-500/10 px-4 py-2 text-sm font-medium text-fuchsia-300 transition-all hover:bg-fuchsia-500/20"
                    >
                      <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                      </svg>
                      {t.exportMD}
                    </button>
                  </div>
                </div>
              </motion.div>
            </>
          )}
        </AnimatePresence>,
        document.body
      )}
    </>
  );
});

const ChatSummarySkeleton = () => (
  <div className="mb-4 rounded-xl border border-purple-500/20 bg-gradient-to-r from-purple-500/5 to-fuchsia-500/5 p-4 backdrop-blur-xl animate-pulse">
    <div className="flex items-center justify-between mb-3">
      <div className="flex items-center gap-2">
        <div className="w-5 h-5 bg-purple-500/20 rounded-full"></div>
        <div className="h-4 w-32 bg-purple-500/20 rounded"></div>
      </div>
      <div className="h-8 w-24 bg-purple-500/20 rounded-lg"></div>
    </div>
    <div className="space-y-4">
      <div className="h-24 bg-cyan-500/10 rounded-xl border border-cyan-500/20"></div>
      <div className="flex gap-2">
        <div className="h-8 w-20 bg-purple-500/10 rounded-xl"></div>
        <div className="h-8 w-24 bg-purple-500/10 rounded-xl"></div>
        <div className="h-8 w-16 bg-purple-500/10 rounded-xl"></div>
      </div>
    </div>
  </div>
);
