"use client";

import React, { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence, useReducedMotion } from "framer-motion";
import { createPortal } from "react-dom";
import type { ChatMessage } from "@/types/chat";
import { useNexusStore } from "@/state/nexusStore";
import jsPDF from "jspdf";
import { Eye, Copy, FileDown, FileText, Check, X, RefreshCw, Loader2, Maximize2, MessageSquare, FileSpreadsheet } from "lucide-react";
import ExcelJS from "exceljs";

interface ChatSummaryProps {
  messages: ChatMessage[];
  sessionId: string;
  onSummaryGenerated?: (summary: string) => void;
  onAddToChat?: (content: string) => void;
}

interface SummaryData {
  quickLook: string;
  keyTopics: string[];
  actionItems: string[];
  userPreferences: string[];
  fullSummary: string;
}

// Static English labels
const LABELS = {
  title: "Conversation Summary",
  quickLook: "Quick Look",
  keyTopics: "Key Topics",
  actionItems: "Action Items",
  userPreferences: "User Preferences",
  fullSummary: "Full Summary",
  generate: "Generate Summary",
  generating: "Generating...",
  copy: "Copy",
  copied: "Copied!",
  exportPDF: "Export PDF",
  exportMD: "Markdown",
  close: "Close",
  expand: "Expand",
  collapse: "Collapse",
  noMessages: "Need at least 2 messages to generate a summary",
  error: "AI failed to generate response. Please try again.",
  generatedBy: "Generated by NEXUS",
  lastUpdated: "Last Updated",
  showInChat: "Show in Chat",
  hideFromChat: "Hide",
  viewContext: "View Context",
};

export const ChatSummary = React.memo(function ChatSummary({
  messages,
  sessionId,
  onSummaryGenerated,
  onAddToChat
}: ChatSummaryProps) {
  // sessionId kept for future use
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const _sessionId = sessionId;
  const { getActiveSession, updateSessionSummary } = useNexusStore();
  const activeSession = getActiveSession();
  const shouldReduceMotion = useReducedMotion();
  const summaryRef = useRef<HTMLDivElement>(null);

  // Load saved summary from session
  const savedSummary = activeSession?.summary;
  const [summaryData, setSummaryData] = useState<SummaryData | null>(() => {
    if (savedSummary) {
      try {
        const parsed = JSON.parse(savedSummary) as SummaryData;
        parsed.keyTopics = parsed.keyTopics || [];
        parsed.actionItems = parsed.actionItems || [];
        parsed.userPreferences = parsed.userPreferences || [];
        parsed.quickLook = parsed.quickLook || "";
        parsed.fullSummary = parsed.fullSummary || "";
        return parsed;
      } catch {
        return null;
      }
    }
    return null;
  });

  const [isLoading, setIsLoading] = useState(false);
  const [isPopupOpen, setIsPopupOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const [showInChat, setShowInChat] = useState(!!savedSummary);
  const [expandedSections, setExpandedSections] = useState({
    quickLook: true,
    keyTopics: true,
    actionItems: true,
    userPreferences: true,
    fullSummary: true
  });
  const [lastUpdated, setLastUpdated] = useState<number | null>(null);
  const [retryCount, setRetryCount] = useState(0);

  // Load summary from session on mount
  useEffect(() => {
    if (activeSession?.summary && !summaryData) {
      try {
        const parsed = JSON.parse(activeSession.summary) as SummaryData;
        parsed.keyTopics = parsed.keyTopics || [];
        parsed.actionItems = parsed.actionItems || [];
        parsed.userPreferences = parsed.userPreferences || [];
        parsed.quickLook = parsed.quickLook || "";
        parsed.fullSummary = parsed.fullSummary || "";
        setSummaryData(parsed);
        setShowInChat(true);
      } catch {
        // Invalid summary, ignore
      }
    }
  }, [activeSession?.summary, summaryData]);

  const generateSummary = React.useCallback(async (silent = false) => {
    if (messages.length < 2) {
      if (!silent) {
        alert(LABELS.noMessages);
      }
      return;
    }

    setIsLoading(true);
    try {
      const response = await fetch("/api/nexus/summarize", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          messages: messages.map((m) => ({ role: m.role, content: m.content })),
        }),
      });

      if (!response.ok) throw new Error("Failed to generate summary");

      const data = await response.json() as SummaryData;
      // Ensure arrays exist
      data.keyTopics = Array.isArray(data.keyTopics) ? data.keyTopics : [];
      data.actionItems = Array.isArray(data.actionItems) ? data.actionItems : [];
      data.userPreferences = Array.isArray(data.userPreferences) ? data.userPreferences : [];
      data.quickLook = data.quickLook || "";
      data.fullSummary = data.fullSummary || "";

      setSummaryData(data);
      setLastUpdated(Date.now());
      setRetryCount(0);

      // Save to session
      updateSessionSummary(JSON.stringify(data));

      // Format summary as a message
      const summaryText = `## 📋 Conversation Summary\n\n**${LABELS.quickLook}:**\n${data.quickLook}\n\n**${LABELS.keyTopics}:**\n${(data.keyTopics || []).map(t => `• ${t}`).join("\n")}\n\n**${LABELS.actionItems}:**\n${(data.actionItems || []).map(a => `✓ ${a}`).join("\n")}\n\n**${LABELS.userPreferences}:**\n${(data.userPreferences || []).map(p => `⭐ ${p}`).join("\n")}\n\n**${LABELS.fullSummary}:**\n${data.fullSummary}`;

      // Add to chat if enabled
      if (showInChat && onAddToChat) {
        onAddToChat(summaryText);
      } else if (!silent && !showInChat) {
        setIsPopupOpen(true);
      }

      onSummaryGenerated?.(data.fullSummary);
    } catch (error) {
      console.error("Failed to generate summary:", error);
      if (!silent) {
        if (retryCount >= 2) {
          alert(LABELS.error);
        }
      }
    } finally {
      setIsLoading(false);
    }
  }, [messages, showInChat, onAddToChat, onSummaryGenerated, retryCount, updateSessionSummary]);

  // Auto-generate summary if enough messages and no summary exists
  useEffect(() => {
    if (messages.length >= 10 && !summaryData && !activeSession?.summary && !isLoading && sessionId) {
      const timer = setTimeout(() => {
        generateSummary(true);
      }, 3000);
      return () => clearTimeout(timer);
    }
  }, [messages.length, summaryData, activeSession?.summary, isLoading, sessionId, generateSummary]);

  // ========== ACTION HANDLERS ==========

  // Copy summary to clipboard with checkmark feedback
  const copySummary = async () => {
    if (!summaryData) return;

    const textToCopy = `QUICK LOOK\n${summaryData.quickLook}\n\nKEY TOPICS\n${(summaryData.keyTopics || []).join("\n")}\n\nACTION ITEMS\n${(summaryData.actionItems || []).join("\n")}\n\nUSER PREFERENCES\n${(summaryData.userPreferences || []).join("\n")}\n\nFULL SUMMARY\n${summaryData.fullSummary}`;

    try {
      await navigator.clipboard.writeText(textToCopy);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  // View in context - scroll to summary
  const viewInContext = () => {
    if (summaryRef.current) {
      summaryRef.current.scrollIntoView({ behavior: "smooth", block: "center" });
    }
    setIsPopupOpen(false);
  };

  // Export to PDF
  const exportToPDF = () => {
    if (!summaryData) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let yPos = margin;

    // Title
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(LABELS.title, pageWidth / 2, yPos, { align: "center" });
    yPos += 15;

    // Quick Look
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(LABELS.quickLook, margin, yPos);
    yPos += 8;
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    const quickLookLines = doc.splitTextToSize(summaryData.quickLook, pageWidth - 2 * margin);
    doc.text(quickLookLines, margin, yPos);
    yPos += quickLookLines.length * 6 + 10;

    // Key Topics
    if ((summaryData.keyTopics || []).length > 0) {
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text(LABELS.keyTopics, margin, yPos);
      yPos += 8;
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      (summaryData.keyTopics || []).forEach((topic) => {
        doc.text(`• ${topic}`, margin + 5, yPos);
        yPos += 6;
      });
      yPos += 5;
    }

    // Action Items
    if ((summaryData.actionItems || []).length > 0) {
      if (yPos > 250) {
        doc.addPage();
        yPos = margin;
      }
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text(LABELS.actionItems, margin, yPos);
      yPos += 8;
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      (summaryData.actionItems || []).forEach((item) => {
        doc.text(`• ${item}`, margin + 5, yPos);
        yPos += 6;
      });
      yPos += 5;
    }

    // User Preferences
    if ((summaryData.userPreferences || []).length > 0) {
      if (yPos > 250) {
        doc.addPage();
        yPos = margin;
      }
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text(LABELS.userPreferences, margin, yPos);
      yPos += 8;
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      (summaryData.userPreferences || []).forEach((pref) => {
        doc.text(`• ${pref}`, margin + 5, yPos);
        yPos += 6;
      });
      yPos += 5;
    }

    // Full Summary
    if (yPos > 250) {
      doc.addPage();
      yPos = margin;
    }
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(LABELS.fullSummary, margin, yPos);
    yPos += 8;
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    const summaryLines = doc.splitTextToSize(summaryData.fullSummary, pageWidth - 2 * margin);
    doc.text(summaryLines, margin, yPos);

    doc.save(`conversation-summary-${Date.now()}.pdf`);
  };

  // Export to Markdown
  const exportToMarkdown = () => {
    if (!summaryData) return;

    const text = `# ${LABELS.title}\n\n**${LABELS.quickLook}**\n${summaryData.quickLook}\n\n**${LABELS.keyTopics}**\n${(summaryData.keyTopics || []).map(t => `- ${t}`).join("\n")}\n\n**${LABELS.actionItems}**\n${(summaryData.actionItems || []).map(i => `- [ ] ${i}`).join("\n")}\n\n**${LABELS.userPreferences}**\n${(summaryData.userPreferences || []).map(p => `- ${p}`).join("\n")}\n\n**${LABELS.fullSummary}**\n${summaryData.fullSummary}`;

    const blob = new Blob([text], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `conversation-summary-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Export to Excel with PRO styling using exceljs
  const handleExportExcel = async () => {
    if (!summaryData) return;

    const workbook = new ExcelJS.Workbook();
    workbook.creator = "NEXUS Analytics PRO";
    workbook.created = new Date();

    // ========== Sheet 1: Data Points ==========
    const dataSheet = workbook.addWorksheet("Data Points", {
      properties: { tabColor: { argb: "FF10B981" } },
    });

    // Extract data from summary
    const categories = summaryData.keyTopics || [];
    const actionItems = summaryData.actionItems || [];
    const preferences = summaryData.userPreferences || [];

    // Define columns with auto-width
    dataSheet.columns = [
      { header: "Category", key: "category", width: 40 },
      { header: "Type", key: "type", width: 15 },
      { header: "Priority", key: "priority", width: 12 },
      { header: "Status", key: "status", width: 15 },
    ];

    // Style header row - Dark background, white bold text
    const headerRow = dataSheet.getRow(1);
    headerRow.eachCell((cell) => {
      cell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "FF1F2937" },
      };
      cell.font = {
        color: { argb: "FFFFFFFF" },
        bold: true,
        size: 11,
      };
      cell.alignment = { vertical: "middle", horizontal: "center" };
      cell.border = {
        bottom: { style: "thin", color: { argb: "FF374151" } },
      };
    });
    headerRow.height = 25;

    // Add Key Topics
    categories.forEach((topic, idx) => {
      const row = dataSheet.addRow({
        category: topic,
        type: "Topic",
        priority: idx < 3 ? "High" : "Normal",
        status: "Identified",
      });
      row.eachCell((cell) => {
        cell.font = { size: 10 };
        cell.alignment = { vertical: "middle", wrapText: true };
      });
    });

    // Add Action Items
    actionItems.forEach((item, idx) => {
      const row = dataSheet.addRow({
        category: item,
        type: "Action",
        priority: idx === 0 ? "Critical" : "High",
        status: "Pending",
      });
      row.eachCell((cell) => {
        cell.font = { size: 10 };
        cell.alignment = { vertical: "middle", wrapText: true };
      });
      // Highlight action items
      row.getCell("type").fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "FFDCFCE7" },
      };
    });

    // Add User Preferences
    preferences.forEach((pref) => {
      const row = dataSheet.addRow({
        category: pref,
        type: "Preference",
        priority: "Normal",
        status: "Noted",
      });
      row.eachCell((cell) => {
        cell.font = { size: 10 };
        cell.alignment = { vertical: "middle", wrapText: true };
      });
      // Highlight preferences
      row.getCell("type").fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "FFF3E8FF" },
      };
    });

    // ========== Sheet 2: Deep Analysis ==========
    const analysisSheet = workbook.addWorksheet("Deep Analysis", {
      properties: { tabColor: { argb: "FF8B5CF6" } },
    });

    // Title
    analysisSheet.mergeCells("A1:D1");
    const titleCell = analysisSheet.getCell("A1");
    titleCell.value = "🧠 NEXUS Strategic Analysis";
    titleCell.font = { bold: true, size: 16, color: { argb: "FF1F2937" } };
    titleCell.alignment = { horizontal: "center", vertical: "middle" };
    analysisSheet.getRow(1).height = 35;

    // Quick Look Section
    analysisSheet.mergeCells("A3:D3");
    const quickLookHeader = analysisSheet.getCell("A3");
    quickLookHeader.value = "📋 Quick Look";
    quickLookHeader.font = { bold: true, size: 12, color: { argb: "FF0891B2" } };

    analysisSheet.mergeCells("A4:D6");
    const quickLookCell = analysisSheet.getCell("A4");
    quickLookCell.value = summaryData.quickLook;
    quickLookCell.font = { size: 11 };
    quickLookCell.alignment = { wrapText: true, vertical: "top" };
    quickLookCell.border = {
      top: { style: "thin", color: { argb: "FFE5E7EB" } },
      left: { style: "thin", color: { argb: "FFE5E7EB" } },
      bottom: { style: "thin", color: { argb: "FFE5E7EB" } },
      right: { style: "thin", color: { argb: "FFE5E7EB" } },
    };

    // Full Summary Section
    analysisSheet.mergeCells("A8:D8");
    const summaryHeader = analysisSheet.getCell("A8");
    summaryHeader.value = "📊 Full Summary & Insights";
    summaryHeader.font = { bold: true, size: 12, color: { argb: "FF7C3AED" } };

    analysisSheet.mergeCells("A9:D20");
    const summaryCell = analysisSheet.getCell("A9");
    summaryCell.value = summaryData.fullSummary;
    summaryCell.font = { size: 11 };
    summaryCell.alignment = { wrapText: true, vertical: "top" };
    summaryCell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FFF9FAFB" },
    };
    summaryCell.border = {
      top: { style: "thin", color: { argb: "FFE5E7EB" } },
      left: { style: "thin", color: { argb: "FFE5E7EB" } },
      bottom: { style: "thin", color: { argb: "FFE5E7EB" } },
      right: { style: "thin", color: { argb: "FFE5E7EB" } },
    };

    // Footer
    analysisSheet.mergeCells("A22:D22");
    const footerCell = analysisSheet.getCell("A22");
    footerCell.value = `Generated by NEXUS Analytics PRO • ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`;
    footerCell.font = { size: 9, italic: true, color: { argb: "FF9CA3AF" } };
    footerCell.alignment = { horizontal: "center" };

    // Set column widths for analysis sheet
    analysisSheet.columns = [
      { width: 30 },
      { width: 30 },
      { width: 30 },
      { width: 30 },
    ];

    // Generate file and download
    const buffer = await workbook.xlsx.writeBuffer();
    const blob = new Blob([buffer], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const dateStr = new Date().toISOString().split("T")[0];
    a.download = `Nexus_Analytics_${dateStr}.xlsx`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const toggleSection = (section: keyof typeof expandedSections) => {
    setExpandedSections(prev => ({
      ...prev,
      [section]: !prev[section]
    }));
  };

  const formatTime = (timestamp: number) => {
    return new Date(timestamp).toLocaleString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit"
    });
  };

  // ========== ACTION BUTTON GRID COMPONENT ==========
  const ActionButtonGrid = () => (
    <div className="grid grid-cols-2 md:grid-cols-5 gap-2 mt-4">
      {/* Analytics PRO - Premium Excel Export */}
      <button
        onClick={handleExportExcel}
        className="relative flex flex-col items-center justify-center gap-1.5 p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-300 hover:bg-emerald-500/20 hover:border-emerald-400/40 hover:text-emerald-200 hover:scale-[1.02] transition-all duration-200 group"
      >
        <FileSpreadsheet className="h-4 w-4" />
        <span className="text-[10px] font-medium uppercase tracking-wide">Analytics</span>
        {/* PRO Badge with pulsing animation on hover */}
        <span className="absolute -top-2 -right-2 px-1.5 py-0.5 bg-gradient-to-r from-amber-400 via-yellow-300 to-cyan-400 text-[8px] font-bold text-black rounded-full shadow-lg group-hover:animate-pulse">
          PRO
        </span>
      </button>

      {/* View Context */}
      <button
        onClick={viewInContext}
        className="flex flex-col items-center justify-center gap-1.5 p-3 rounded-xl bg-white/5 border border-white/10 text-white/70 hover:bg-white/10 hover:text-white hover:scale-[1.02] transition-all duration-200"
      >
        <Eye className="h-4 w-4" />
        <span className="text-[10px] font-medium uppercase tracking-wide">View Context</span>
      </button>

      {/* Copy Summary */}
      <button
        onClick={copySummary}
        className={`flex flex-col items-center justify-center gap-1.5 p-3 rounded-xl border transition-all duration-200 hover:scale-[1.02] ${copied
          ? "bg-emerald-500/20 border-emerald-500/30 text-emerald-300"
          : "bg-white/5 border-white/10 text-white/70 hover:bg-white/10 hover:text-white"
          }`}
      >
        {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
        <span className="text-[10px] font-medium uppercase tracking-wide">
          {copied ? "Copied!" : "Copy"}
        </span>
      </button>

      {/* Export PDF */}
      <button
        onClick={exportToPDF}
        className="flex flex-col items-center justify-center gap-1.5 p-3 rounded-xl bg-white/5 border border-white/10 text-white/70 hover:bg-white/10 hover:text-white hover:scale-[1.02] transition-all duration-200"
      >
        <FileDown className="h-4 w-4" />
        <span className="text-[10px] font-medium uppercase tracking-wide">Export PDF</span>
      </button>

      {/* Export Markdown */}
      <button
        onClick={exportToMarkdown}
        className="flex flex-col items-center justify-center gap-1.5 p-3 rounded-xl bg-white/5 border border-white/10 text-white/70 hover:bg-white/10 hover:text-white hover:scale-[1.02] transition-all duration-200"
      >
        <FileText className="h-4 w-4" />
        <span className="text-[10px] font-medium uppercase tracking-wide">Markdown</span>
      </button>
    </div>
  );

  // Show skeleton if loading and no data yet
  if (isLoading && !summaryData && showInChat) {
    return <ChatSummarySkeleton />;
  }

  // Show summary in chat if enabled
  if (showInChat && summaryData) {
    return (
      <div ref={summaryRef} className="mb-4 rounded-xl border border-purple-500/20 bg-gradient-to-r from-purple-500/5 to-fuchsia-500/5 p-4 backdrop-blur-xl" dir="ltr">
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <svg className="w-5 h-5 text-purple-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            <span className="text-sm font-semibold text-purple-300">{LABELS.title}</span>
            {lastUpdated && (
              <span className="text-xs text-purple-400/60">
                {LABELS.lastUpdated}: {formatTime(lastUpdated)}
              </span>
            )}
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => generateSummary(false)}
              disabled={isLoading}
              className="px-3 py-1.5 text-xs bg-gradient-to-r from-purple-600/20 to-fuchsia-600/20 hover:from-purple-600/30 hover:to-fuchsia-600/30 text-purple-200 rounded-lg transition-all duration-300 disabled:opacity-50 hover:scale-105 active:scale-95 border border-purple-500/30 hover:border-purple-400/50"
              title={LABELS.generate}
            >
              {isLoading ? (
                <div className="flex items-center gap-1.5">
                  <Loader2 className="h-3 w-3 animate-spin text-purple-300" />
                  <span className="text-[10px] font-medium">{LABELS.generating}</span>
                </div>
              ) : (
                <div className="flex items-center gap-1.5">
                  <RefreshCw className="w-3 h-3" />
                  <span className="text-[10px] font-medium">{LABELS.generate}</span>
                </div>
              )}
            </button>
            <button
              onClick={() => setShowInChat(false)}
              className="px-3 py-1.5 text-xs bg-white/5 hover:bg-white/10 text-white/60 rounded-lg transition-all duration-300 hover:scale-105 active:scale-95 border border-white/10 hover:border-white/20"
              title={LABELS.hideFromChat}
            >
              <div className="flex items-center gap-1.5">
                <X className="w-3 h-3" />
                <span className="text-[10px] font-medium">{LABELS.hideFromChat}</span>
              </div>
            </button>
            <button
              onClick={() => setIsPopupOpen(true)}
              className="px-3 py-1.5 text-xs bg-gradient-to-r from-purple-600/30 via-fuchsia-600/25 to-purple-600/30 hover:from-purple-600/40 hover:via-fuchsia-600/35 hover:to-purple-600/40 text-purple-100 rounded-lg transition-all duration-300 hover:scale-105 active:scale-95 border border-purple-500/40 hover:border-purple-400/60 hover:shadow-[0_0_15px_rgba(168,85,247,0.2)]"
            >
              <div className="flex items-center gap-1.5">
                <Maximize2 className="w-3 h-3" />
                <span className="text-[10px] font-medium">{LABELS.expand}</span>
              </div>
            </button>
          </div>
        </div>

        {/* Quick Look */}
        <div className="mb-4 rounded-xl border border-cyan-500/30 bg-gradient-to-br from-cyan-500/10 to-cyan-900/5 p-4 backdrop-blur-sm">
          <div className="flex items-center gap-2 mb-3">
            <div className="p-1.5 rounded-lg bg-cyan-500/20 border border-cyan-400/30">
              <Eye className="h-4 w-4 text-cyan-300" />
            </div>
            <h3 className="text-xs font-bold uppercase tracking-wider text-cyan-300 bg-gradient-to-r from-cyan-300 to-cyan-200 bg-clip-text text-transparent">{LABELS.quickLook}</h3>
          </div>
          <p className="text-sm leading-relaxed text-white/90 pl-2 border-l-2 border-cyan-500/30">{summaryData.quickLook}</p>
        </div>

        {/* Key Topics */}
        {(summaryData.keyTopics || []).length > 0 && (
          <div className="mb-4">
            <div className="flex items-center gap-2 mb-3">
              <div className="p-1.5 rounded-lg bg-purple-500/20 border border-purple-400/30">
                <svg className="h-4 w-4 text-purple-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 20l4-16m2 16l4-16M6 9h14M4 15h14" />
                </svg>
              </div>
              <h3 className="text-xs font-bold uppercase tracking-wider text-purple-300 bg-gradient-to-r from-purple-300 to-fuchsia-200 bg-clip-text text-transparent">{LABELS.keyTopics}</h3>
            </div>
            <div className="flex flex-wrap gap-2">
              {(summaryData.keyTopics || []).slice(0, 4).map((topic, idx) => (
                <span key={idx} className="px-3 py-1.5 rounded-xl border border-purple-500/30 bg-gradient-to-r from-purple-500/10 to-fuchsia-500/5 text-xs font-medium text-purple-200 hover:from-purple-500/20 hover:to-fuchsia-500/10 transition-all duration-300 hover:scale-105 hover:shadow-[0_0_15px_rgba(168,85,247,0.15)]">
                  • {topic}
                </span>
              ))}
              {(summaryData.keyTopics || []).length > 4 && (
                <span className="px-3 py-1.5 rounded-xl border border-purple-500/40 bg-gradient-to-r from-purple-600/20 to-fuchsia-600/15 text-xs font-medium text-purple-300 hover:shadow-[0_0_15px_rgba(168,85,247,0.2)] transition-all">
                  +{(summaryData.keyTopics || []).length - 4} more
                </span>
              )}
            </div>
          </div>
        )}

        {/* Action Items */}
        {(summaryData.actionItems || []).length > 0 && (
          <div className="mb-4">
            <div className="flex items-center gap-2 mb-3">
              <div className="p-1.5 rounded-lg bg-emerald-500/20 border border-emerald-400/30">
                <Check className="h-4 w-4 text-emerald-300" />
              </div>
              <h3 className="text-xs font-bold uppercase tracking-wider text-emerald-300 bg-gradient-to-r from-emerald-300 to-cyan-200 bg-clip-text text-transparent">{LABELS.actionItems}</h3>
            </div>
            <div className="space-y-2">
              {(summaryData.actionItems || []).slice(0, 3).map((item, idx) => (
                <div key={idx} className="flex items-start gap-3 p-2 rounded-lg border border-emerald-500/20 bg-gradient-to-r from-emerald-500/5 to-emerald-900/5 hover:from-emerald-500/10 hover:to-emerald-900/10 transition-all duration-300 group">
                  <div className="p-1 rounded-md bg-emerald-500/20 border border-emerald-400/30 group-hover:bg-emerald-500/30 group-hover:border-emerald-400/50 transition-colors">
                    <Check className="h-3 w-3 text-emerald-300" />
                  </div>
                  <span className="text-xs font-medium text-white/90 flex-1">{item}</span>
                </div>
              ))}
              {(summaryData.actionItems || []).length > 3 && (
                <div className="text-xs font-medium text-emerald-300/70 text-center pt-1">
                  +{(summaryData.actionItems || []).length - 3} more action items
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    );
  }

  // Summary generation button (when no summary exists or hidden)
  return (
    <>
      <div className="mb-4 rounded-xl border border-purple-500/20 bg-gradient-to-r from-purple-500/5 to-fuchsia-500/5 p-3 backdrop-blur-xl" dir="ltr">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <svg className="w-4 h-4 text-purple-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            <span className="text-xs font-semibold text-purple-300">{LABELS.title}</span>
          </div>
          <button
            onClick={() => generateSummary(false)}
            disabled={isLoading}
            className="px-4 py-2 text-xs font-medium bg-gradient-to-r from-purple-600/40 via-fuchsia-600/30 to-purple-600/40 hover:from-purple-600/50 hover:via-fuchsia-600/40 hover:to-purple-600/50 text-purple-100 rounded-xl transition-all duration-300 disabled:opacity-50 transform-gpu will-change-transform border border-purple-500/40 hover:border-purple-400/60 hover:shadow-[0_0_20px_rgba(168,85,247,0.3)] hover:scale-105 active:scale-95 group relative overflow-hidden"
          >
            {/* Shine effect */}
            <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/20 to-transparent translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-1000" />

            {isLoading ? (
              <div className="flex items-center gap-2 relative z-10">
                <Loader2 className="h-3.5 w-3.5 animate-spin text-purple-200" />
                <span className="font-semibold">{LABELS.generating}</span>
              </div>
            ) : (
              <div className="flex items-center gap-2 relative z-10">
                <FileText className="w-3.5 h-3.5 text-purple-200" />
                <span className="font-semibold">{LABELS.generate}</span>
              </div>
            )}
          </button>
        </div>
      </div>

      {/* Glassmorphism Popup */}
      {typeof window !== "undefined" && createPortal(
        <AnimatePresence>
          {isPopupOpen && summaryData && (
            <>
              {/* Backdrop */}
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: shouldReduceMotion ? 0 : 0.2 }}
                className="fixed inset-0 z-[99998] bg-black/60 backdrop-blur-sm"
                onClick={() => setIsPopupOpen(false)}
                aria-hidden="true"
              />

              {/* Popup */}
              <motion.div
                initial={{ opacity: 0, scale: shouldReduceMotion ? 1 : 0.95, y: shouldReduceMotion ? 0 : 20 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                exit={{ opacity: 0, scale: shouldReduceMotion ? 1 : 0.95, y: shouldReduceMotion ? 0 : 20 }}
                transition={shouldReduceMotion ? { duration: 0 } : { type: "spring", damping: 25, stiffness: 300 }}
                className="fixed left-1/2 top-1/2 z-[99999] w-[90vw] max-w-2xl -translate-x-1/2 -translate-y-1/2 rounded-3xl border border-white/20 bg-black/80 backdrop-blur-2xl shadow-2xl shadow-black/50 transform-gpu will-change-transform"
                role="dialog"
                aria-modal="true"
                aria-label={LABELS.title}
                dir="ltr"
              >
                {/* Header */}
                <div className="flex items-center justify-between border-b border-white/10 bg-black/40 p-5">
                  <h2 className="text-lg font-bold tracking-wide text-white/90">{LABELS.title}</h2>
                  <div className="flex items-center gap-2">
                    {lastUpdated && (
                      <span className="text-xs text-white/40">
                        {LABELS.lastUpdated}: {formatTime(lastUpdated)}
                      </span>
                    )}
                    <button
                      onClick={() => setIsPopupOpen(false)}
                      className="rounded-lg p-1.5 text-white/50 transition-colors hover:bg-white/10 hover:text-white"
                      aria-label={LABELS.close}
                    >
                      <X className="h-5 w-5" />
                    </button>
                  </div>
                </div>

                {/* Content */}
                <div className="max-h-[60vh] overflow-y-auto p-5 [scrollbar-width:thin] [scrollbar-color:rgba(148,163,184,0.35)_transparent]">
                  {/* Quick Look Card */}
                  <div className="mb-6 rounded-2xl border border-cyan-500/30 bg-gradient-to-br from-cyan-500/10 to-purple-500/10 p-4 backdrop-blur-xl">
                    <div className="mb-2 flex items-center justify-between gap-2">
                      <div className="flex items-center gap-2">
                        <Eye className="h-5 w-5 text-cyan-400" />
                        <h3 className="text-sm font-bold uppercase tracking-wider text-cyan-300">{LABELS.quickLook}</h3>
                      </div>
                      <button
                        onClick={() => toggleSection('quickLook')}
                        className="text-white/50 hover:text-white transition-colors"
                      >
                        <svg className={`h-4 w-4 transition-transform ${expandedSections.quickLook ? 'rotate-180' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                        </svg>
                      </button>
                    </div>
                    {expandedSections.quickLook && (
                      <p className="text-sm leading-relaxed text-white/90">{summaryData.quickLook}</p>
                    )}
                  </div>

                  {/* Key Topics */}
                  {(summaryData.keyTopics || []).length > 0 && (
                    <div className="mb-6">
                      <div className="flex items-center justify-between mb-3">
                        <h3 className="text-sm font-bold uppercase tracking-wider text-purple-300">{LABELS.keyTopics}</h3>
                        <button
                          onClick={() => toggleSection('keyTopics')}
                          className="text-white/50 hover:text-white transition-colors"
                        >
                          <svg className={`h-4 w-4 transition-transform ${expandedSections.keyTopics ? 'rotate-180' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                          </svg>
                        </button>
                      </div>
                      {expandedSections.keyTopics && (
                        <div className="space-y-2">
                          {(summaryData.keyTopics || []).map((topic, idx) => (
                            <div key={idx} className="rounded-lg border border-white/10 bg-white/5 px-4 py-2 text-sm text-white/80">
                              • {topic}
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  )}

                  {/* Action Items */}
                  {(summaryData.actionItems || []).length > 0 && (
                    <div className="mb-6">
                      <div className="flex items-center justify-between mb-3">
                        <h3 className="text-sm font-bold uppercase tracking-wider text-emerald-300">{LABELS.actionItems}</h3>
                        <button
                          onClick={() => toggleSection('actionItems')}
                          className="text-white/50 hover:text-white transition-colors"
                        >
                          <svg className={`h-4 w-4 transition-transform ${expandedSections.actionItems ? 'rotate-180' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                          </svg>
                        </button>
                      </div>
                      {expandedSections.actionItems && (
                        <div className="space-y-2">
                          {(summaryData.actionItems || []).map((item, idx) => (
                            <div key={idx} className="rounded-lg border border-emerald-500/20 bg-emerald-500/5 px-4 py-2 text-sm text-white/80">
                              ✓ {item}
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  )}

                  {/* User Preferences */}
                  {(summaryData.userPreferences || []).length > 0 && (
                    <div className="mb-6">
                      <div className="flex items-center justify-between mb-3">
                        <h3 className="text-sm font-bold uppercase tracking-wider text-fuchsia-300">{LABELS.userPreferences}</h3>
                        <button
                          onClick={() => toggleSection('userPreferences')}
                          className="text-white/50 hover:text-white transition-colors"
                        >
                          <svg className={`h-4 w-4 transition-transform ${expandedSections.userPreferences ? 'rotate-180' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                          </svg>
                        </button>
                      </div>
                      {expandedSections.userPreferences && (
                        <div className="space-y-2">
                          {(summaryData.userPreferences || []).map((pref, idx) => (
                            <div key={idx} className="rounded-lg border border-fuchsia-500/20 bg-fuchsia-500/5 px-4 py-2 text-sm text-white/80">
                              ⭐ {pref}
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  )}

                  {/* Full Summary */}
                  <div>
                    <div className="flex items-center justify-between mb-3">
                      <h3 className="text-sm font-bold uppercase tracking-wider text-white/70">{LABELS.fullSummary}</h3>
                      <button
                        onClick={() => toggleSection('fullSummary')}
                        className="text-white/50 hover:text-white transition-colors"
                      >
                        <svg className={`h-4 w-4 transition-transform ${expandedSections.fullSummary ? 'rotate-180' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                        </svg>
                      </button>
                    </div>
                    {expandedSections.fullSummary && (
                      <p className="text-sm leading-relaxed text-white/80 whitespace-pre-wrap">{summaryData.fullSummary}</p>
                    )}
                  </div>

                  {/* Action Button Grid */}
                  <ActionButtonGrid />
                </div>

                {/* Footer */}
                <div className="flex items-center justify-between border-t border-white/10 bg-black/40 p-4">
                  <div className="text-xs text-white/40">
                    {LABELS.generatedBy}
                  </div>
                  <button
                    onClick={() => {
                      setShowInChat(true);
                      setIsPopupOpen(false);
                    }}
                    className="flex items-center gap-2 rounded-lg border border-purple-500/30 bg-purple-500/10 px-4 py-2 text-sm font-medium text-purple-300 transition-all hover:bg-purple-500/20 hover:scale-[1.02]"
                  >
                    <MessageSquare className="h-4 w-4" />
                    {LABELS.showInChat}
                  </button>
                </div>
              </motion.div>
            </>
          )}
        </AnimatePresence>,
        document.body
      )}
    </>
  );
});

const ChatSummarySkeleton = () => (
  <div className="mb-4 rounded-xl border border-purple-500/20 bg-gradient-to-r from-purple-500/5 to-fuchsia-500/5 p-4 backdrop-blur-xl animate-pulse" dir="ltr">
    <div className="flex items-center justify-between mb-3">
      <div className="flex items-center gap-2">
        <div className="w-5 h-5 bg-purple-500/20 rounded-full"></div>
        <div className="h-4 w-32 bg-purple-500/20 rounded"></div>
      </div>
      <div className="h-8 w-24 bg-purple-500/20 rounded-lg"></div>
    </div>
    <div className="space-y-4">
      <div className="h-24 bg-cyan-500/10 rounded-xl border border-cyan-500/20"></div>
      <div className="flex gap-2">
        <div className="h-8 w-20 bg-purple-500/10 rounded-xl"></div>
        <div className="h-8 w-24 bg-purple-500/10 rounded-xl"></div>
        <div className="h-8 w-16 bg-purple-500/10 rounded-xl"></div>
      </div>
    </div>
  </div>
);
